on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          brew install coreutils
          set -x
          dir=$(dirname $(grealpath $(which pod)))
          v=$(sw_vers -productVersion)
          if [ "$v" = "`echo -e "$v\n10.999" | sort -V | head -n1`" ]; then
            dir=$(grealpath $dir/../gems)
          else
            dir=$(grealpath $dir/../libexec/gems)
          fi
          uname -a
          f=$(grep --include=\*.rb -rnwl $dir -e "unless lib_name.end_with?('.a')")
          sed -i '' "s/unless lib_name.end_with?('.a') && lib_name.start_with?('lib')/unless (lib_name.end_with?('.a') || lib_name.end_with?('.dylib')) \&\& File.basename(lib_name).start_with?('lib')/g" $f
          f=$(grep --include=\*.rb -rnwl $dir -e "validate_nonempty_patterns(attr_name, :error)")
          sed -i '' "s/validate_nonempty_patterns(attr_name, :error)/(attr_name.to_s == 'vendored_libraries') || validate_nonempty_patterns(attr_name, :error)/g" $f
          cat $f
          pod trunk push --allow-warnings test.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${secrets.COCOAPODS_TRUNK_TOKEN}
